# Generated by Django 5.1.3 on 2024-11-16 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0002_product_additional_images_product_colors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='additional_images',
            field=models.ImageField(blank=True, max_length=4, null=True, upload_to='product_image/other/'),
        ),
    ]
