# Generated by Django 5.1.3 on 2024-11-16 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0003_alter_product_additional_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='additional_images',
        ),
    ]
