# Generated by Django 5.1.3 on 2024-11-16 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0004_remove_product_additional_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='additional_image1',
            field=models.ImageField(blank=True, null=True, upload_to='product_image/other/'),
        ),
        migrations.AddField(
            model_name='product',
            name='additional_image2',
            field=models.ImageField(blank=True, null=True, upload_to='product_image/other/'),
        ),
        migrations.AddField(
            model_name='product',
            name='additional_image3',
            field=models.ImageField(blank=True, null=True, upload_to='product_image/other/'),
        ),
        migrations.AddField(
            model_name='product',
            name='additional_image4',
            field=models.ImageField(blank=True, null=True, upload_to='product_image/other/'),
        ),
    ]
