# Generated by Django 5.1.3 on 2024-11-16 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0005_product_additional_image1_product_additional_image2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
