# Generated by Django 5.1.3 on 2024-11-28 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0011_color_hex_code_alter_color_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='color',
            name='hex_code',
        ),
    ]
