# Generated by Django 5.1.3 on 2024-11-29 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0012_remove_color_hex_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_msg', models.CharField(max_length=200, unique=True)),
            ],
        ),
    ]
