# Generated by Django 5.1.3 on 2024-11-14 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0015_orders_order_alter_category_id_alter_coupon_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
