# Generated by Django 5.1.3 on 2024-12-08 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0016_herosection'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSectionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hero_images/')),
                ('hero_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ecom.herosection')),
            ],
        ),
    ]
