# Generated by Django 5.1.3 on 2024-11-15 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0018_sub_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sub_category',
            name='product_image',
        ),
    ]
